const PAGINATION = {
  TABLE_MANAGE: 5,
};

const CAMPAIGN_VISIBILITY = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
};

const CAMPAIGN_STATUS = {
  DRAFT: 'DRAFT',
  WAITING: 'WAITING',
  RUNNING: 'RUNNING',
  PAUSE: 'PAUSE',
  END: 'END',
};

export { PAGINATION, CAMPAIGN_VISIBILITY, CAMPAIGN_STATUS };
