export default {
  OVERVIEW: '/admin/',
  SERVICE_MANAGE: '/admin/service-manage',
  CAMPAIGN_MANAGE: '/admin/campaign-manage',
  CREATE_CAMPAIGN: '/admin/campaigns/create',
  CAMPAIGN_PARTICIPANT: '/admin/campaigns/:campaignId/participant',
  AUDIO_MANAGE: '/admin/audios/manage',
  ASR_SCENARIO_MANAGE: '/admin/asr/scenarios',
  CHATBOT_CAMPAIGN_RESULT: '/admin/campaigns/:campaignId/chatbot/result',
  FAQ_INTENT_CATEGORIES: '/admin/faq/categories',
  FAQ_INTENT_CATEGORIES_CREATE: '/admin/faq/categories/create',
  FAQ_INTENT_CATEGORIES_EDIT: '/admin/faq/categories/:categoryId/edit',
  NLU_MANAGE_INTENTS: '/admin/nlu-manage/intents',
  FAQ_INTENT_MANAGE: '/admin/faq/intents',
};
